version: '2'
services:
  redis-cluster:
    environment:
     IP: ${REDIS_CLUSTER_IP}
     SENTINEL: ${REDIS_USE_SENTINEL}
     STANDALONE: ${REDIS_USE_STANDALONE}
    build:
      context: .
      args:
        redis_version: '5.0.5'
    hostname: server
    network_mode: "host"
    ports:
      - '7000-7007:7000-7007'
      - '5000-5002:5000-5002'
